[package]
name = "slam_jam"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
escapi = "4.0.0"
fltk = "1.3.32"
opencv-ros-camera = "0.14.0"
time = "0.3.20"
